version: "3.3"

services:
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080

  node:
    image: node:10
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    user: 1000:1000

  nginx:
    ports:
    - 80:80

  db:
    ports:
      - 5432:5432
