parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  SymfonyCraft\JobBoard\Tests\:
    resource: '../tests/'

  SymfonyCraft\JobBoard\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  SymfonyCraft\JobBoard\Infrastructure\Controller\:
    resource: '../src/Infrastructure/Controller/'
    tags: [ 'controller.service_arguments' ]

  _instanceof:
    SymfonyCraft\JobBoard\Application\Query\QueryHandler:
      tags:
        - { name: messenger.message_handler, bus: query.bus }
    SymfonyCraft\JobBoard\Application\Command\CommandHandler:
      tags:
        - { name: messenger.message_handler, bus: command.bus }
    SymfonyCraft\JobBoard\Application\Event\EventHandler:
      tags:
        - { name: messenger.message_handler, bus: event.bus }

  SymfonyCraft\JobBoard\Domain\JobCollection:
    '@SymfonyCraft\JobBoard\Infrastructure\Persistence\InMemory\InMemoryJobCollection'
  SymfonyCraft\JobBoard\Domain\ApplicantCollection:
    '@SymfonyCraft\JobBoard\Tests\UseCase\Fake\FakeApplicantCollection'
  SymfonyCraft\JobBoard\Domain\CompanyCollection:
    '@SymfonyCraft\JobBoard\Tests\UseCase\Fake\FakeCompanyCollection'
